Fix an error with ParcellationTerminologyVersion (which is embedded, not sure why it isn't linked).
Error context:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[11], line 4
      1 import fairgraph.openminds.ephys as ephys
      3 file_170529_1b = [f for f in dataset_version.repository.files if "170529_1b" in f.name][0]
----> 4 recording_info = file_170529_1b.is_location_of.resolve(kg_client, scope="any", follow_links={"recorded_with": {}})

File /srv/main-spack-instance-2402/spack/var/spack/environments/ebrains-24-04/.spack-env/view/lib/python3.8/site-packages/fairgraph/kgquery.py:110, in KGQuery.resolve(self, client, size, from_index, space, scope, use_cache, follow_links)
    108 objects: List[KGObject] = []
    109 for cls in self.classes:
--> 110     query = cls.generate_query(client=client, filters=self.filter, space=space, follow_links=follow_links)
    111     instances = client.query(
    112         query=query,
    113         size=size,
    114         from_index=from_index,
    115         scope=scope,
    116     ).data
    117     objects.extend(cls.from_kg_instance(instance_data, client) for instance_data in instances)

AttributeError: type object 'ParcellationTerminologyVersion' has no attribute 'generate_query'
```